# [Aire puro]


> El aire puro, el sol, la abstinencia, el descanso, el ejercicio, un régimen alimenticio conveniente, el agua y la confianza en el poder divino son los verdaderos remedios. Todos debieran conocer los agentes que la naturaleza provee como remedios, y saber aplicarlos. 
> 
> --- El Ministerio de Curación p.89

 Aliento de Vida 


en la sección \@ref(luz-solar)
 

“Y Dios el Señor formó al hombre del polvo de la tierra, y sopló en su nariz hálito de vida, y el hombre se convirtió en un ser viviente.” 

‭‭Génesis‬ ‭2:7‬ ‭NVI‬‬ 

Dios puso el soplo de vida en el ser humano, ese soplo sigue vivo en cada uno de nosotros, cada vez que respiramos es una muestra de que en Dios esta la vida y la mantenemos por este medio.  

El ser humano respiró, quiero pensar que Adan tuvo una inhalación muy profunda, pues estaba recibiendo del mismísimo creador el aire con todo lo que necesitaba para poder vivir. Y después de expirar, volvió a respirar y aunque ya no venía del mismo creador lo que respiraba si tenía el aire limpio que necesitaba para seguir vivo por todo lo que Dios acababa de hacer, todos los árboles y plantas que mantenían el ambiente en un estado de perfecta armonía para que el ser humano pudiera seguir respirando el aire más puro nunca después encontrado en la historia de la humanidad.  

El la atmósfera que recubre la tierra encontramos las condiciones adecuadas para que el ser humano pueda continuar respirando para mantener la vida.  

Cuando el ser humano ya no puede respirar, cuando deja de introducir oxígeno a su cuerpo, entonces muere.  

 


El oxigeno es indispensable para la vida. Basta dejar de respirar 40 segundos para darse cuenta que se necesita  

 

 

 

 

 
